name = "hoverboard"
main = "./dist/worker.mjs"
compatibility_date = "2024-05-23"

[build]
command = "npm run build:debug"

# DEV
[[kv_namespaces]]
binding = "DENYLIST"
id = "f4eb0eca32e14e28b643604a82e00cb3"
preview_id = "f4eb0eca32e14e28b643604a82e00cb3"


# STAGING!
[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
routes = [
	{ pattern = "hoverboard-staging.dag.haus", custom_domain = true },
]
tail_consumers = [
  { service = "loki-staging" }
]

[env.staging.vars]
CONTENT_CLAIMS_URL='https://staging.claims.web3.storage/'

[env.staging.build]
command = "npm run build"

[[env.staging.kv_namespaces]]
binding = "DENYLIST"
id = "f4eb0eca32e14e28b643604a82e00cb3"
preview_id = "f4eb0eca32e14e28b643604a82e00cb3"


# PROD!
[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
routes = [
	{ pattern = "hoverboard.dag.haus", custom_domain = true },
]
tail_consumers = [
  { service = "loki-production" }
]

[[env.production.kv_namespaces]]
binding = "DENYLIST"
id = "785cf627e913468ca5319523ae929def"

[env.production.build]
command = "npm run build"
