name = "hoverboard"
main = "src/worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = [
  # https://developers.cloudflare.com/workers/configuration/compatibility-dates/#nodejs-compatibility-flag
  "nodejs_compat"
]

# DEV
[vars]
CONTENT_CLAIMS = 'https://staging.claims.web3.storage'
DYNAMO_TABLE = 'staging-ep-v1-blocks-cars-position'
DYNAMO_REGION = 'us-west-2'

[[r2_buckets]]
binding = "CARPARK"
bucket_name = "carpark-staging-0"
preview_bucket_name = "carpark-staging-0"

[[kv_namespaces]]
binding = "DENYLIST"
id = "f4eb0eca32e14e28b643604a82e00cb3"
preview_id = "f4eb0eca32e14e28b643604a82e00cb3"


# STAGING!
[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
routes = [
	{ pattern = "hoverboard-staging.dag.haus", custom_domain = true },
]
tail_consumers = [
  { service = "loki-staging" }
]

[env.staging.vars]
DYNAMO_TABLE = 'staging-ep-v1-blocks-cars-position'
DYNAMO_REGION = 'us-west-2'

[[env.staging.r2_buckets]]
binding = "CARPARK"
bucket_name = "carpark-staging-0"
preview_bucket_name = "carpark-staging-0"

[[env.staging.kv_namespaces]]
binding = "DENYLIST"
id = "f4eb0eca32e14e28b643604a82e00cb3"
preview_id = "f4eb0eca32e14e28b643604a82e00cb3"


# PROD!
[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
routes = [
	{ pattern = "hoverboard.dag.haus", custom_domain = true },
]
tail_consumers = [
  { service = "loki-production" }
]

[env.production.vars]
DYNAMO_TABLE = 'prod-ep-v1-blocks-cars-position'
DYNAMO_REGION = 'us-west-2'

[[env.production.r2_buckets]]
binding = "CARPARK"
bucket_name = "carpark-prod-0"

[[env.production.kv_namespaces]]
binding = "DENYLIST"
id = "785cf627e913468ca5319523ae929def"
