name = "hoverboard"
main = "src/worker.js"
compatibility_date = "2023-06-28"

# dev settings
[vars]
PEER_ID_JSON = '{"id":"Qmcv3CsJAN8ptXR8vm5a5GRrzkHGjaEUF9cQRGzYptMwzp","privKey":"CAASpgkwggSiAgEAAoIBAQDrJS8e0E/eXiYqlE65jS/H4NNuvXwKGPTQlThKcJ1h92g/HjgbEjL52Zux82amHVfaKI9Vw+5BiC+trwpne/4mHl4d0YD6Ndeo8VjRbEnrlhBx2pWTyvof1dZeR522TGq8vc63ek9kJRY6Hdu4yBuvr7VK7XSzbLoew9Hfun+BZMN13+miQ04EHAjOfvVoDUyR78Sk3ljM8Nqaq3dBPmkuBY5ADjbkpf94N7SuopjvEKnMtryDUhA/jxJU7+6/m5IN5mag2OgZZFov5XxKwdc1KWkLH+zjo7pWyJ4+VRpVwv1vcPy/Qs1/Xf61B4lvNFOOBPE3nI+kwu1jBauPuNc7AgMBAAECggEACQUIjBsJLmWzjV5H1RA87Rmvooep4Dr+Q1BBau9HM1Ly3kxdKSb02C/DrB+eKDnnoX8PXQawQDZmY4FJNU9Eso3nXN5NsYIq7Nh61h7J9oS4pZ6DQN8JUEQokHT0OU/Cgzsq6uHumfSnXuVSBQIQAT0MmeorRal93imqKxpcsNpHFSZdi1yNAWE9yxpXlF1LAkkZDmlDqdLg2zsAJQDZf/JnBak45i/E7AnDD/rR5t+VKeWupC9QA52X7MyAp9xeJCJmRgrHs9Bj/uQF5ozQqCBaIgekbh+OCxpzTqjpVNGwWuOxIUsQpAGqCpGzGIECbw5XN/qOEsuxpt45e3mtYQKBgQDy+t8vEi3AXCfpYRuI2+GNQI/6Uch4LJ6ohP0CHNLTtKpXEbBPfBAGryHWrR3SNTxjF7myFM5YR+V5eRBslkRJt9JSN11kAe1rA98SvmlHB3dnISgLKbrmg+fXvg3rEf6n57x8+Dsh9zwxQyHjTg2MArDdicnIyvdslYazeH+zSwKBgQD3vtZ/hql37bNLSIoJl+FiSHl57KoZSA/RIE0uVkqJtgCG4f6O1AMvyCDa7vtly460RtyaKg6ADW/jepsOydiOKKm1E/5MgG7ZttbrhPDfoXeHCEPzHs0J2I9D4OXQ8uSVbIZWKEcP5702lpHX5E0iWIVaErFTZEkuSazYwYUF0QKBgGcqYWyo+Uf9WOzcUEaRpXjF+tu7sbRkrZC7tnkZJ+K/iLujRQrakCtmXKW7pzfDZrpkLnIQJ3SQQjyLTI/uVVw/ckt6Omrl7ppLcIGS2zxPTUE6cLgcpcCOLPgLN/mhEFDWMc+VzfWj9ais6kyKrXHPCq1lfYmFs/wkmKbG+OF1AoGAWh0CLHSw47yEQNfrzb1+757pAJ5C6Ns7VZfoOviMODcJTgaZ7x3S4uhqevf+XXKDP7OevjyZ9Z3tmtKX3/MvX9YOlJznHLCCoZJN7nD2pIE41tb80EvdzL0Gr2v4a95NosRMwL35yyFBw79U4TBbliiYqMCv22NY8ws9YcJSPmECgYALiFLv7Z90NOYsi0pZh3koxKtYEOEmaNIqOlBbXP2J0eo6wJKFR0nbu8t+s5poJUiU9t+e1V+Lyjy6aFg/fWvc9b9ZB9fm+MIltHVaFGsC7cMhPn3Q8demehkQvTl2XBxnhOobPdFxxJsjpDpShOgRfKBzwLEH5arLmDUrw6FNuQ==","pubKey":"CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDrJS8e0E/eXiYqlE65jS/H4NNuvXwKGPTQlThKcJ1h92g/HjgbEjL52Zux82amHVfaKI9Vw+5BiC+trwpne/4mHl4d0YD6Ndeo8VjRbEnrlhBx2pWTyvof1dZeR522TGq8vc63ek9kJRY6Hdu4yBuvr7VK7XSzbLoew9Hfun+BZMN13+miQ04EHAjOfvVoDUyR78Sk3ljM8Nqaq3dBPmkuBY5ADjbkpf94N7SuopjvEKnMtryDUhA/jxJU7+6/m5IN5mag2OgZZFov5XxKwdc1KWkLH+zjo7pWyJ4+VRpVwv1vcPy/Qs1/Xf61B4lvNFOOBPE3nI+kwu1jBauPuNc7AgMBAAE="}'
LISTEN_ADDR = '/dns4/localhost/tcp/8787/ws'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.consumers]]
# queue = "my-queue"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/platform/services
# [[services]]
# binding = "MY_SERVICE"
# service = "/api/*"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
# [[migrations]]
# tag = "v1"
# new_classes = ["MyDurableObject"]
