name: setup-npm
description: Setup node and npm

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: 20
        cache: 'npm'
    - run: npm ci
      shell: bash
